# Generated by Django 5.0.3 on 2024-03-11 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charts',
            fields=[
                ('chartId', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=20)),
                ('scannedCount', models.IntegerField(default=0)),
                ('detectedCount', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Intrusions',
            fields=[
                ('intrusionId', models.AutoField(primary_key=True, serialize=False)),
                ('packetDetails', models.JSONField(default=dict)),
                ('intrusionType', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('notificationDetail', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('alertId', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('intrusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NidsModels.intrusions')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('role', models.CharField(choices=[('Network Admin', 'Network Admin'), ('Security Analyst', 'Security Analyst'), ('Guest', 'Guest')], max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
